### ISSUE TITLE
Chrono Timer(Chrono::SECONDS, false);

### ISSUE THREAD

**Issue by vangalvin** [thomasfredericks/Chrono#6] opened 2017-03-12 11:44 UTC
Setting the timer so it will not start does not seem to work. Is this the correct way to implement it?

I am using the latest version but getting this

exit status 1
no matching function for call to 'Chrono::Chrono(Chrono::Resolution, bool)'

**Comment by BPDanek** [comment] 2019-07-24 17:22
You could use the stop() function, and then call reset() when you need to start timing. The documentation suggests the timer is starts upon instantiation by design.

**Comment by sofian** [comment] 2019-12-01 17:25
That's strange, it should work. Can you send me an example code so I can reproduce the bug?

**Comment by sofian** [comment] 2019-12-01 17:27
In fact you are right, the constructor with Resolution enum does not allow for the startNow option. Let me see if I can fix this.

**Comment by sofian** [comment] 2019-12-01 17:39
This has been fixed in the new release (v1.2.0).

**Closed as completed by sofian** 2019-12-01 17:39 UTC
Labels: bug
